apiVersion: v1
kind: Namespace
metadata:
  name: develop-http-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: standalone-http-server
  name: standalone-http-server
  namespace: develop-http-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: standalone-http-server
  template:
    metadata:
      labels:
        app: standalone-http-server
    spec:
      containers:
        - image: registry.hub.docker.com/vsmuralidhar/standalone-http-server:latest
          name: standalone-http-server
          ports:
            - containerPort: 6880
---
apiVersion: v1
kind: Service
metadata:
  name: standalone-http-server
  namespace: develop-http-server
spec:
  selector:
    app: standalone-http-server
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 6880
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  labels:
    app: standalone-http-server
  name: standalone-http-server
  namespace: develop-http-server
spec:
  rules:
    - host: vs-local.minikube.com
      http:
        paths:
          - backend:
              service:
                name: standalone-http-server
                port:
                  number: 80
            path: /
            pathType: Prefix

